# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_entertainer',
            field=models.CharField(default='Entertainer', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='Antrim', max_length=10),
        ),
    ]
