# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171204_2100'),
        ('accounts', '0003_auto_20171209_1956'),
    ]

    operations = [
    ]
