# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20171211_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booked_entertainers',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
