# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_booked_entertainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='booked_entertainers',
            field=models.CharField(default='No Bookings', max_length=255),
        ),
    ]
