# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entertainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainer',
            name='genre',
            field=models.CharField(
                choices=[('GTRK', 'Rock'), ('GTML', 'Metal'), ('GTPK', 'Punk'), ('GTBS', 'Blues'), ('GTJZ', 'Jazz'),
                         ('GTCL', 'Classical'), ('GTRE', 'Reggae'), ('GTSA', 'Ska'), ('GTDE', 'Dance'),
                         ('GTFK', 'Funk')], default='ROCK', max_length=4),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='description',
            field=models.CharField(choices=[('ETBD', 'Band'), ('ETSM', 'Solo Musician')], default='BAND', max_length=4),
        ),
    ]