# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0004_auto_20180113_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainer',
            name='image1',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='image1/'),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='image2',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='image3',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='image4',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='image5',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='profile_image',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='profile/'),
        ),
    ]
