# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0004_auto_20171117_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainer',
            name='description',
            field=models.CharField(choices=[('BAND', 'Band'), ('SOLO_PERFORMER', 'Solo Performer')], default='BAND', max_length=14),
        ),
    ]
