# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0005_auto_20180202_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainer',
            name='image2',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='img2/'),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='image3',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='img3/'),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='image4',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='img4/'),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='image5',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='img5/'),
        ),
    ]
