# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0007_auto_20180219_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainer',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='entertainer',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='entertainer',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='entertainer',
            name='image5',
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/image1/'),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/'),
        ),
    ]
