# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 16:02
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0007_auto_20171117_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainer',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ENGLISH', 'English'), ('IRISH', 'Irish'), ('FRENCH', 'French'), ('SPANISH', 'Spanish'), ('GERMAN', 'German')], default='ENGLISH', max_length=35),
        ),
    ]
