# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0008_entertainer_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainer',
            name='gig_length_from',
            field=models.PositiveIntegerField(choices=[('60', '60'), ('90', '90'), ('120', '120'), ('180', '180'), ('240', '240')], default=60, max_length=3),
        ),
        migrations.AddField(
            model_name='entertainer',
            name='gig_length_to',
            field=models.PositiveIntegerField(choices=[('60', '60'), ('90', '90'), ('120', '120'), ('180', '180'), ('240', '240')], default=90, max_length=3),
        ),
        migrations.AddField(
            model_name='entertainer',
            name='music',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Original', 'Original'), ('Covers', 'Covers'), ('Comedy', 'Comedy'), ('Parody', 'Parody')], default='Originals', max_length=29),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Irish', 'Irish'), ('French', 'French'), ('Spanish', 'Spanish'), ('German', 'German')], default='English', max_length=35),
        ),
    ]
