# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0010_auto_20180219_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainer',
            name='image1',
            field=models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images/image1/'),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images/profile/'),
        ),
    ]
