# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0011_auto_20180220_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainer',
            name='image2',
            field=models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images/image2/'),
        ),
        migrations.AddField(
            model_name='entertainer',
            name='image3',
            field=models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images/image3/'),
        ),
        migrations.AddField(
            model_name='entertainer',
            name='image4',
            field=models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images/image4/'),
        ),
        migrations.AddField(
            model_name='entertainer',
            name='image5',
            field=models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images/image5/'),
        ),
    ]
