# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0012_auto_20180220_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entertainer',
            old_name='soundcloud_audio',
            new_name='soundcloud_embed_audio',
        ),
        migrations.RenameField(
            model_name='entertainer',
            old_name='youtube_video',
            new_name='youtube_embed_video',
        ),
    ]
