# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0013_auto_20171122_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainer',
            name='image',
        ),
        migrations.AddField(
            model_name='entertainer',
            name='image1',
            field=models.ImageField(default='media/1/no-image.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='entertainer',
            name='image2',
            field=models.ImageField(default='media/no-image.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='entertainer',
            name='image3',
            field=models.ImageField(default='media/no-image.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='entertainer',
            name='image4',
            field=models.ImageField(default='media/no-image.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='entertainer',
            name='image5',
            field=models.ImageField(default='media/no-image.png', upload_to='media/'),
        ),
    ]
