# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0013_auto_20180220_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainer',
            name='description',
            field=models.CharField(choices=[('Band', 'Band'), ('Solo', 'Solo'), ('Comedian', 'Commedian')], default='Band', max_length=14),
        ),
    ]
