# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0017_auto_20171122_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainer',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Metal', 'Metal'), ('Punk', 'Punk'), ('Blues', 'Blues'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Reggae', 'Reggae'), ('Ska', 'Ska'), ('Dance', 'Dance'), ('Funk', 'Funk'), ('Trad', 'Trad'), ('Country', 'Country'), ('Soul', 'Soul'), ('Other', 'Other')], default='Rock', max_length=9),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='image1',
            field=models.ImageField(default='media/img1/no_image.png', upload_to='media/img1/'),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='image2',
            field=models.ImageField(default='media/img2/no_image.png', upload_to='media/img2/'),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='image3',
            field=models.ImageField(default='media/img3/no_image.png', upload_to='media/img3/'),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='image4',
            field=models.ImageField(default='media/img4/no_image.png', upload_to='media/img4/'),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='image5',
            field=models.ImageField(default='media/img5/no_image.png', upload_to='media/img5/'),
        ),
    ]
