# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0018_auto_20171122_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainer',
            name='travel_distance',
            field=models.CharField(choices=[('same county', 'same county'), ('same province', 'same province'), ('nationwide', 'nationwide')], default='nationwide', max_length=13),
        ),
    ]
