# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0019_entertainer_travel_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainer',
            name='max_price',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600')], default='500', max_length=3),
        ),
        migrations.AddField(
            model_name='entertainer',
            name='min_price',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600')], default='100', max_length=3),
        ),
    ]
