# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0024_entertainer_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainer',
            name='soundcloud_audio',
            field=models.TextField(default='https://soundcloud.com/'),
        ),
    ]
