# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0026_auto_20171123_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainer',
            name='youtube_video',
            field=models.TextField(default='https://www.youtube.com'),
        ),
    ]
