# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0027_entertainer_youtube_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainer',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Metal', 'Metal'), ('Punk', 'Punk'), ('Blues', 'Blues'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Reggae', 'Reggae'), ('Ska', 'Ska'), ('Dance', 'Dance'), ('Electronic', 'Electronic'), ('Folk', 'Folk'), ('Pop', 'Pop'), ('Funk', 'Funk'), ('Trad', 'Trad'), ('Country', 'Country'), ('Soul', 'Soul'), ('RnB', 'RnB'), ('Other', 'Other')], default='Rock', max_length=11),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
