# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 00:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entertainers', '0028_auto_20171202_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainer',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
