# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 00:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0031_auto_20171203_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainer',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
