# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0032_auto_20171203_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainer',
            name='user',
        ),
    ]
