# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 21:06
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0034_entertainer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainer',
            name='user',
            field=models.OneToOneField(default=accounts.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
