# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 21:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0035_auto_20171204_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
