# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0036_auto_20171204_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainer',
            name='user',
        ),
    ]
