# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entertainers', '0037_remove_entertainer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
