# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0033_auto_20171211_0018'),
        ('entertainers', '0038_entertainer_user'),
    ]

    operations = [
    ]
