# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0039_merge_20171211_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainer',
            name='description',
            field=models.CharField(choices=[('Band', 'Band'), ('Solo', 'Solo'), ('Comedian', 'Commedian'), ("Children's Entertainer", "Children's Entertainer")], default='Band', max_length=14),
        ),
    ]
