# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainers', '0040_auto_20171212_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainer',
            name='dislikes_total',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='entertainer',
            name='likes_total',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='soundcloud_audio',
            field=models.TextField(default='<iframe width="100%" height="300" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/209382959&amp;color=%23ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;show_teaser=true&amp;visual=true"></iframe>'),
        ),
        migrations.AlterField(
            model_name='entertainer',
            name='youtube_video',
            field=models.TextField(default='<iframe width="560" height="315" src="https://www.youtube.com/embed/xaE2wV-HMxs" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>'),
        ),
    ]
